from dataclasses import dataclass


@dataclass
class Config:
    """
    Configuration class for VIKGA.

    Attributes
    ----------
    n_min : int, default=50
        Number of individuals in the initial population.
    n_max : int, default=1000
        Maximum number of individuals in the population.
    n_gen : int, default=100
         Maximum number of generations.
    n_cross : int, default=20
        Number of offsprings generated by crossover.
    n_mute : int, default=10
        Number of offsprings generated by mutation.
    sample : str, default="lhs"
        Initial population sampling method.
    crossover : str, default="sbx"
        Crossover operator.
    eta_c : float, default=20.0
        Spread factor for the crossover operation.
    mutation : str, default="pm"
        Mutation operator.
    eta_m : float, default=5.0
        Spread factor for the mutation operation.
    p : float, default=0.5
        Mutation probability.
    d_mins : float, default=0.1
        Neighborhood distance for local minima identification.
    n_mins : int, default=10
        Minimum number of neighbors for local minima identification.
    display : bool, default=True
        Flag to display progress in the console.
    save : bool, default=True
        Flag to save results.
    save_dir : str, default=None
        Path to the results folder.
    decimals : int, default=4
        Number of decimals for precision.
    parallel : bool, default=False
        Flag to enable multiprocessing.
    n_proc : int, default=2
        Number of processes for parallel execution.
    """

    n_min: int = 100
    n_max: int = 1000
    n_gen: int = 500
    n_cross: int = 10
    n_mute: int = 6
    sample: str = "lhs"
    crossover: str = "sbx"
    eta_c: float = 15.0
    mutation: str = "pm"
    eta_m: float = 1.0
    pm: float = 0.3
    d_mins: float = 0.1
    n_mins: int = 10
    display: bool = True
    save: bool = True
    save_dir: str = None
    parallel: bool = False
    n_proc: int = 2
