from dataclasses import dataclass


@dataclass
class Config:
    """
    Configuration class for VIKGA.

    Attributes
    ----------
    sample : str, default="lhs"
        Initial population sampling method (e.g., "lhs", "random").
    n_min : int, default=50
        Number of individuals in the initial population.
    n_max : int, default=1000
        Maximum number of individuals allowed in the population.
    n_gen : int, default=1000
         Maximum number of generations allowed.
    crossover : str, default="sbx"
        Crossover operator (e.g., "sbx", "uniform").
    n_selec : int, default=10
        Number of individuals selected for tournament selection.
    n_cross : int, default=10
        Number of offspring couples generated by crossover.
    n_crowd : int, default=10
        Crowd size for second parent selection.
    eta_c : float, default=15.0
        Spread factor for the crossover operation.
    mutation : str, default="pm"
        Mutation operator (e.g., "pm", "gaussian").
    n_mute : int, default=10
        Number of offspring generated by mutation.
    eta_m : float, default=5.0
        Spread factor for the mutation operation.
    p : float, default=0.75
        Mutation probability.
    d0 : float, default=0.1
        Addition distance around bad individuals.
    alpha : float, default=1.0
        Multiplication factor for constraint handling.
    d_mins : float, default=0.1
        Distance threshold for local minima identification.
    n_mins : int, default=10
        Minimum number of neighbors for local minima identification.
    display : bool, default=True
        Flag to display progress in the console.
    plot : bool, default=True
        Flag to plot results.
    save : bool, default=True
        Flag to save results.
    save_dir : str, default=None
        Path to the results folder.
    decimals : int, default=4
        Number of decimals for precision.
    n_conv : int, default=300
        Number of generations for convergence criteria.
    parallel : bool, default=False
        Flag to enable multiprocessing.
    n_proc : int, default=2
        Number of processes for parallel execution.
    """

    sample: str = "lhs"
    n_min: int = 50
    n_max: int = 1000
    n_gen: int = 1000
    crossover: str = "sbx"
    n_selec: int = 10
    n_cross: int = 10
    n_crowd: int = 10
    eta_c: float = 15.0
    mutation: str = "pm"
    n_mute: int = 10
    eta_m: float = 5.0
    p: float = 0.75
    d0: float = 0.1
    alpha: float = 1.0
    d_mins: float = 0.1
    n_mins: int = 10
    display: bool = True
    plot: bool = True
    save: bool = True
    save_dir: str = None
    decimals: int = 4
    n_conv: int = 300
    parallel: bool = False
    n_proc: int = 2
