from dataclasses import dataclass


@dataclass
class Config:
    """
    Configuration parameters for VIKGA.

    Attributes
    ----------
    n_min : int, default=100
        Minimum number of individuals in the population.
    n_max : int, default=1000
        Maximum number of individuals in the population.
    n_gen : int, default=500
        Maximum number of generations.
    n_cross : int, default=10
        Number of offspring generated by crossover at each generation.
    n_mute : int, default=6
        Number of offspring generated by mutation at each generation.
    sample : str, default="lhs"
        Initial population sampling strategy.
    crossover : str, default="sbx"
        Crossover operator.
    eta_c : float, default=15.0
        Distribution index controlling the spread of the crossover operator.
    mutation : str, default="pm"
        Mutation operator.
    eta_m : float, default=1.0
        Distribution index controlling the spread of the mutation operator.
    pm : float, default=0.3
        Mutation probability.
    d_mins : float, default=0.1
        Distance threshold used to identify local minima.
    n_mins : int, default=10
        Minimum number of neighboring solutions required for local minima identification.
    display : bool, default=True
        Whether to display optimization progress in the console.
    save : bool, default=True
        Whether to save optimization results.
    save_dir : str or None, default=None
        Directory where results are saved. If ``None``, a default location is used.
    parallel : bool, default=False
        Whether to evaluate individuals in parallel.
    n_proc : int, default=2
        Number of processes used for parallel evaluation when ``parallel`` is enabled.
    """

    n_min: int = 100
    n_max: int = 1000
    n_gen: int = 500
    n_cross: int = 10
    n_mute: int = 6
    sample: str = "lhs"
    crossover: str = "sbx"
    eta_c: float = 15.0
    mutation: str = "pm"
    eta_m: float = 1.0
    pm: float = 0.3
    d_mins: float = 0.1
    n_mins: int = 10
    display: bool = True
    save: bool = True
    save_dir: str = None
    parallel: bool = False
    n_proc: int = 2
